import React, { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { jsPDF } from 'jspdf';

const NEGATIVE_STATEMENTS = [
  'I am not good at studying.',
  'My memory is very weak.',
  'Math is too difficult for me.',
  'I always forget what I study.',
  "I can't concentrate on anything.",
  'I am not intelligent enough to learn this.',
  'I will definitely fail this exam.',
  'Everyone learns faster than me.',
  'I made a mistake, so I am bad at this subject.',
  'I can never learn programming.',
];

function Reflects() {
  const navigate = useNavigate();
  const [name, setName] = useState('');
  const [responses, setResponses] = useState(
    Array(NEGATIVE_STATEMENTS.length).fill('')
  );

  const handleChange = (index, value) => {
    const updated = [...responses];
    updated[index] = value;
    setResponses(updated);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const usableWidth = pageWidth - margin * 2;
    let y = 25;

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(11, 42, 91); // #0B2A5B
    doc.text('Positive Affirmations', pageWidth / 2, y, { align: 'center' });
    y += 10;

    // Subtitle
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text('Turn Negative Self-Talk into Positive Self-Talk', pageWidth / 2, y, { align: 'center' });
    y += 8;

    // Name
    if (name.trim()) {
      doc.setFontSize(11);
      doc.setTextColor(60, 60, 60);
      doc.text(`Name: ${name.trim()}`, pageWidth / 2, y, { align: 'center' });
    }
    y += 12;

    // Entries
    NEGATIVE_STATEMENTS.forEach((statement, idx) => {
      // Check if we need a new page
      if (y > 260) {
        doc.addPage();
        y = 25;
      }

      // Negative statement
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(200, 50, 50);
      const negText = `${idx + 1}. ❌ ${statement}`;
      const negLines = doc.splitTextToSize(negText, usableWidth);
      doc.text(negLines, margin, y);
      y += negLines.length * 5 + 2;

      // Positive response
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(34, 139, 34);
      const posText = `   ✅ ${responses[idx] || '(not filled)'}`;
      const posLines = doc.splitTextToSize(posText, usableWidth);
      doc.text(posLines, margin, y);
      y += posLines.length * 5 + 8;
    });

    // Footer
    y += 5;
    if (y > 270) {
      doc.addPage();
      y = 25;
    }
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Super Learner Academy', pageWidth / 2, 285, { align: 'center' });

    const fileName = `Possitive Affirmation_${name.trim() || 'Student'}.pdf`;
    doc.save(fileName);
  };

  const allFilled = responses.every(r => r.trim() !== '') && name.trim() !== '';

  return (
    <div className="app-container">
      <div style={styles.pageContainer}>
        {/* Header */}
        <div style={styles.header}>
          <button onClick={() => navigate('/')} style={styles.backButton}>
            ← Home
          </button>
          <h1 style={styles.title}>🪞 Reflects</h1>
          <p style={styles.subtitle}>
            Turn Negative Self-Talk into Positive Self-Talk
          </p>
        </div>

        <div style={styles.formCard}>
          {/* Name field */}
          <div style={styles.nameSection}>
            <label style={styles.nameLabel}>Your Name</label>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Enter your name"
              style={styles.nameInput}
            />
          </div>

          {/* Instructions */}
          <div style={styles.instructions}>
            <p>
              Read each negative statement below and rewrite it as a{' '}
              <strong>positive affirmation</strong>. Believe in your growth!
            </p>
          </div>

          {/* Statements */}
          <div style={styles.statementsContainer}>
            {NEGATIVE_STATEMENTS.map((statement, idx) => (
              <div key={idx} style={styles.statementRow}>
                <div style={styles.negativeText}>
                  <span style={styles.number}>{idx + 1}.</span>
                  <span style={styles.redX}>❌</span>
                  <span>{statement}</span>
                </div>
                <div style={styles.responseRow}>
                  <span style={styles.arrow}>→</span>
                  <input
                    type="text"
                    value={responses[idx]}
                    onChange={(e) => handleChange(idx, e.target.value)}
                    placeholder="Write your positive version..."
                    style={styles.responseInput}
                  />
                </div>
              </div>
            ))}
          </div>

          {/* Download Button */}
          <button
            onClick={handleDownloadPDF}
            disabled={!allFilled}
            style={{
              ...styles.downloadButton,
              opacity: allFilled ? 1 : 0.5,
              cursor: allFilled ? 'pointer' : 'not-allowed',
            }}
          >
            📥 Download as PDF
          </button>
          {!allFilled && (
            <p style={styles.hint}>
              Fill in your name and all responses to enable download.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

const styles = {
  pageContainer: {
    minHeight: '100vh',
    padding: '30px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '24px',
  },
  header: {
    textAlign: 'center',
    position: 'relative',
    width: '100%',
    maxWidth: '800px',
  },
  backButton: {
    position: 'absolute',
    left: 0,
    top: 0,
    background: 'rgba(255,255,255,0.15)',
    border: 'none',
    color: 'white',
    padding: '8px 16px',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    backdropFilter: 'blur(10px)',
  },
  title: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: '2rem',
    fontWeight: '800',
    color: 'white',
    marginBottom: '6px',
  },
  subtitle: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: '1rem',
  },
  formCard: {
    background: 'white',
    borderRadius: '24px',
    padding: '36px 30px',
    width: '100%',
    maxWidth: '800px',
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  nameSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  nameLabel: {
    fontWeight: '700',
    fontSize: '0.95rem',
    color: '#0B2A5B',
  },
  nameInput: {
    padding: '12px 16px',
    border: '2px solid #e0e0e0',
    borderRadius: '12px',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border-color 0.2s',
    maxWidth: '350px',
  },
  instructions: {
    background: '#f0f7ff',
    border: '1px solid #d0e4ff',
    borderRadius: '12px',
    padding: '14px 18px',
    fontSize: '0.95rem',
    color: '#333',
    lineHeight: '1.5',
  },
  statementsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  statementRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '14px 16px',
    background: '#fafafa',
    borderRadius: '12px',
    border: '1px solid #eee',
  },
  negativeText: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#c0392b',
  },
  number: {
    fontWeight: '700',
    color: '#555',
    minWidth: '20px',
  },
  redX: { fontSize: '1rem' },
  responseRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    paddingLeft: '28px',
  },
  arrow: {
    fontSize: '1.2rem',
    color: '#27ae60',
    fontWeight: '700',
  },
  responseInput: {
    flex: 1,
    padding: '10px 14px',
    border: '2px solid #d4edda',
    borderRadius: '10px',
    fontSize: '0.95rem',
    outline: 'none',
    transition: 'border-color 0.2s',
    background: '#f8fff8',
  },
  downloadButton: {
    background: 'linear-gradient(135deg, #1E5EFF 0%, #0B2A5B 100%)',
    color: 'white',
    border: 'none',
    padding: '16px 36px',
    borderRadius: '30px',
    fontSize: '1.05rem',
    fontWeight: '700',
    cursor: 'pointer',
    alignSelf: 'center',
    boxShadow: '0 4px 15px rgba(30, 94, 255, 0.3)',
    marginTop: '10px',
  },
  hint: {
    textAlign: 'center',
    fontSize: '0.85rem',
    color: '#999',
  },
};

export default Reflects;
