import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { jsPDF } from 'jspdf';

const NEGATIVE_STATEMENTS = [
  'I am not good at studying.',
  'My memory is very weak.',
  'Math is too difficult for me.',
  'I always forget what I study.',
  "I can't concentrate on anything.",
  'I am not intelligent enough to learn this.',
  'I will definitely fail this exam.',
  'Everyone learns faster than me.',
  'I made a mistake, so I am bad at this subject.',
  'I can never learn programming.',
];

// Shared PDF header with logo
function addPDFHeader(doc, pageWidth) {
  let y = 15;
  // Logo
  const logoUrl = `${window.location.origin}${import.meta.env.BASE_URL}Logo.png`;
  try {
    // We'll add text branding instead of image to avoid async issues
  } catch (e) {}
  
  // Brand name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(11, 42, 91);
  doc.text('Super Learner Academy', pageWidth / 2, y, { align: 'center' });
  y += 6;
  doc.setDrawColor(255, 107, 0);
  doc.setLineWidth(0.8);
  doc.line(60, y, pageWidth - 60, y);
  y += 10;
  return y;
}

function Reflects() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('affirmation');
  
  // Affirmation state
  const [name, setName] = useState('');
  const [responses, setResponses] = useState(Array(NEGATIVE_STATEMENTS.length).fill(''));

  // Action Plan state
  const [apName, setApName] = useState('');
  const [apDay, setApDay] = useState('');
  const [apReflection, setApReflection] = useState('');
  const [apActions, setApActions] = useState(['', '', '']);

  // Learning Reflection state
  const [lrName, setLrName] = useState('');
  const [lrDate, setLrDate] = useState('');
  const [lrTopic, setLrTopic] = useState('');
  const [lrLearnings, setLrLearnings] = useState(['', '', '']);
  const [lrTodos, setLrTodos] = useState(['', '', '', '', '']);

  // ===== PDF: Positive Affirmation =====
  const handleDownloadAffirmation = () => {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const usableWidth = pageWidth - margin * 2;
    let y = addPDFHeader(doc, pageWidth);

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(11, 42, 91);
    doc.text('Positive Affirmations', pageWidth / 2, y, { align: 'center' });
    y += 8;

    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text('Turn Negative Self-Talk into Positive Self-Talk', pageWidth / 2, y, { align: 'center' });
    y += 8;

    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    doc.text('Name: ' + (name.trim() || 'Student'), pageWidth / 2, y, { align: 'center' });
    y += 14;

    // Entries
    NEGATIVE_STATEMENTS.forEach((statement, idx) => {
      if (y > 255) { doc.addPage(); y = addPDFHeader(doc, pageWidth); }

      // Negative
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(192, 57, 43);
      const negText = (idx + 1) + '. [Negative] ' + statement;
      const negLines = doc.splitTextToSize(negText, usableWidth);
      doc.text(negLines, margin, y);
      y += negLines.length * 5 + 3;

      // Positive
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(39, 174, 96);
      const posText = '   [Positive] ' + (responses[idx] || '(not filled)');
      const posLines = doc.splitTextToSize(posText, usableWidth);
      doc.text(posLines, margin, y);
      y += posLines.length * 5 + 10;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Super Learner Academy', pageWidth / 2, 287, { align: 'center' });

    doc.save('Possitive Affirmation_' + (name.trim() || 'Student') + '.pdf');
  };

  // ===== PDF: Action Plan =====
  const handleDownloadActionPlan = () => {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const usableWidth = pageWidth - margin * 2;
    let y = addPDFHeader(doc, pageWidth);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(11, 42, 91);
    doc.text('Action Plan', pageWidth / 2, y, { align: 'center' });
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    doc.text('Name: ' + (apName.trim() || 'Student'), margin, y);
    y += 7;
    doc.text('Day: ' + (apDay.trim() || '-'), margin, y);
    y += 12;

    // Reflection
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(106, 61, 232);
    doc.text('Reflection Statement', margin, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const refLines = doc.splitTextToSize(apReflection || '(not filled)', usableWidth);
    doc.text(refLines, margin, y);
    y += refLines.length * 5 + 10;

    // Action Plans
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(52, 168, 83);
    doc.text('Action Plans', margin, y);
    y += 8;

    apActions.forEach((action, idx) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const actionText = 'Action Plan ' + (idx + 1) + ': ' + (action || '(not filled)');
      const lines = doc.splitTextToSize(actionText, usableWidth);
      doc.text(lines, margin, y);
      y += lines.length * 5 + 6;
    });

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Super Learner Academy', pageWidth / 2, 287, { align: 'center' });

    doc.save('Action Plan_' + (apName.trim() || 'Student') + '.pdf');
  };

  // ===== PDF: Learning Reflection =====
  const handleDownloadLearning = () => {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const usableWidth = pageWidth - margin * 2;
    let y = addPDFHeader(doc, pageWidth);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(11, 42, 91);
    doc.text('My Learning Reflection', pageWidth / 2, y, { align: 'center' });
    y += 12;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    doc.text('Name: ' + (lrName.trim() || '-'), margin, y);
    y += 7;
    doc.text('Date: ' + (lrDate.trim() || '-'), margin, y);
    y += 7;
    doc.text('Session Topic: ' + (lrTopic.trim() || '-'), margin, y);
    y += 14;

    // Top 3 Learnings
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(255, 107, 0);
    doc.text('My Top 3 Learnings', margin, y);
    y += 8;

    const learningLabels = [
      'The most important thing I learned today:',
      'Another useful thing I learned:',
      'Something I want to remember for a long time:',
    ];
    learningLabels.forEach((label, idx) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);
      doc.text((idx + 1) + '. ' + label, margin, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      const lines = doc.splitTextToSize(lrLearnings[idx] || '(not filled)', usableWidth - 5);
      doc.text(lines, margin + 5, y);
      y += lines.length * 5 + 8;
    });

    // Top 5 Todos
    y += 4;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 94, 255);
    doc.text('My Top 5 Todos for Tomorrow', margin, y);
    y += 8;

    lrTodos.forEach((todo, idx) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const todoText = (idx + 1) + '. ' + (todo || '(not filled)');
      const lines = doc.splitTextToSize(todoText, usableWidth);
      doc.text(lines, margin, y);
      y += lines.length * 5 + 5;
    });

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Super Learner Academy', pageWidth / 2, 287, { align: 'center' });

    doc.save('Learning Reflection_' + (lrName.trim() || 'Student') + '.pdf');
  };

  const affirmationFilled = responses.every(r => r.trim() !== '') && name.trim() !== '';
  const actionPlanFilled = apName.trim() && apReflection.trim() && apActions.every(a => a.trim());
  const learningFilled = lrName.trim() && lrLearnings.every(l => l.trim()) && lrTodos.every(t => t.trim());

  return (
    <div className="app-container">
      <div style={styles.pageContainer}>
        {/* Header */}
        <div style={styles.header}>
          <button onClick={() => navigate('/')} style={styles.backButton}>
            ← Home
          </button>
          <h1 style={styles.title}>🪞 Reflects</h1>
          <p style={styles.subtitle}>Self-reflection tools for growth</p>
        </div>

        {/* Tab Buttons */}
        <div style={styles.tabBar}>
          <button
            onClick={() => setActiveTab('affirmation')}
            style={activeTab === 'affirmation' ? styles.tabActive : styles.tabInactive}
          >
            Positive Affirmation
          </button>
          <button
            onClick={() => setActiveTab('actionplan')}
            style={activeTab === 'actionplan' ? styles.tabActive : styles.tabInactive}
          >
            Action Plan
          </button>
          <button
            onClick={() => setActiveTab('learning')}
            style={activeTab === 'learning' ? styles.tabActive : styles.tabInactive}
          >
            Learning Reflection
          </button>
        </div>

        {/* ===== TAB 1: Positive Affirmation ===== */}
        {activeTab === 'affirmation' && (
          <div style={styles.formCard}>
            <h2 style={styles.formTitle}>Turn Negative Self-Talk into Positive</h2>
            <div style={styles.nameSection}>
              <label style={styles.nameLabel}>Your Name</label>
              <input type="text" value={name} onChange={(e) => setName(e.target.value)}
                placeholder="Enter your name" style={styles.nameInput} />
            </div>
            <div style={styles.statementsContainer}>
              {NEGATIVE_STATEMENTS.map((statement, idx) => (
                <div key={idx} style={styles.statementRow}>
                  <div style={styles.negativeText}>
                    <span style={styles.number}>{idx + 1}.</span>
                    <span style={{ color: '#c0392b' }}>X</span>
                    <span>{statement}</span>
                  </div>
                  <div style={styles.responseRow}>
                    <span style={styles.arrow}>→</span>
                    <input type="text" value={responses[idx]}
                      onChange={(e) => { const u = [...responses]; u[idx] = e.target.value; setResponses(u); }}
                      placeholder="Write your positive version..."
                      style={styles.responseInput} />
                  </div>
                </div>
              ))}
            </div>
            <button onClick={handleDownloadAffirmation}
              disabled={!affirmationFilled}
              style={{ ...styles.downloadButton, opacity: affirmationFilled ? 1 : 0.5, cursor: affirmationFilled ? 'pointer' : 'not-allowed' }}>
              Download PDF
            </button>
            {!affirmationFilled && <p style={styles.hint}>Fill in your name and all responses to download.</p>}
          </div>
        )}

        {/* ===== TAB 2: Action Plan ===== */}
        {activeTab === 'actionplan' && (
          <div style={styles.formCard}>
            <h2 style={styles.formTitle}>Action Plan</h2>
            <div style={styles.fieldGroup}>
              <label style={styles.nameLabel}>Your Name</label>
              <input type="text" value={apName} onChange={(e) => setApName(e.target.value)}
                placeholder="Enter your name" style={styles.nameInput} />
            </div>
            <div style={styles.fieldGroup}>
              <label style={styles.nameLabel}>Day (e.g., Day 1, Day 2...)</label>
              <input type="text" value={apDay} onChange={(e) => setApDay(e.target.value)}
                placeholder="Day 1" style={styles.nameInput} />
            </div>
            <div style={styles.fieldGroup}>
              <label style={styles.nameLabel}>Reflection Statement</label>
              <textarea value={apReflection} onChange={(e) => setApReflection(e.target.value)}
                placeholder="Write your reflection for today..."
                style={styles.textarea} rows={4} />
            </div>
            {apActions.map((action, idx) => (
              <div key={idx} style={styles.fieldGroup}>
                <label style={styles.nameLabel}>Action Plan {idx + 1}</label>
                <input type="text" value={action}
                  onChange={(e) => { const u = [...apActions]; u[idx] = e.target.value; setApActions(u); }}
                  placeholder={`Action plan ${idx + 1}...`}
                  style={styles.nameInput} />
              </div>
            ))}
            <button onClick={handleDownloadActionPlan}
              disabled={!actionPlanFilled}
              style={{ ...styles.downloadButton, opacity: actionPlanFilled ? 1 : 0.5, cursor: actionPlanFilled ? 'pointer' : 'not-allowed' }}>
              Download PDF
            </button>
            {!actionPlanFilled && <p style={styles.hint}>Fill in all fields to download.</p>}
          </div>
        )}

        {/* ===== TAB 3: Learning Reflection ===== */}
        {activeTab === 'learning' && (
          <div style={styles.formCard}>
            <h2 style={styles.formTitle}>My Learning Reflection</h2>
            <div style={styles.fieldGroup}>
              <label style={styles.nameLabel}>Name</label>
              <input type="text" value={lrName} onChange={(e) => setLrName(e.target.value)}
                placeholder="Your name" style={styles.nameInput} />
            </div>
            <div style={styles.fieldGroup}>
              <label style={styles.nameLabel}>Date</label>
              <input type="date" value={lrDate} onChange={(e) => setLrDate(e.target.value)}
                style={styles.nameInput} />
            </div>
            <div style={styles.fieldGroup}>
              <label style={styles.nameLabel}>Session Topic</label>
              <input type="text" value={lrTopic} onChange={(e) => setLrTopic(e.target.value)}
                placeholder="What was today's session about?" style={styles.nameInput} />
            </div>

            <h3 style={styles.subHeading}>My Top 3 Learnings</h3>
            {['The most important thing I learned today:',
              'Another useful thing I learned:',
              'Something I want to remember for a long time:'].map((label, idx) => (
              <div key={idx} style={styles.fieldGroup}>
                <label style={styles.smallLabel}>{idx + 1}. {label}</label>
                <textarea value={lrLearnings[idx]}
                  onChange={(e) => { const u = [...lrLearnings]; u[idx] = e.target.value; setLrLearnings(u); }}
                  placeholder="Write here..." style={styles.textarea} rows={2} />
              </div>
            ))}

            <h3 style={styles.subHeading}>My Top 5 Todos for Tomorrow</h3>
            {lrTodos.map((todo, idx) => (
              <div key={idx} style={styles.fieldGroup}>
                <label style={styles.smallLabel}>Todo {idx + 1}</label>
                <input type="text" value={todo}
                  onChange={(e) => { const u = [...lrTodos]; u[idx] = e.target.value; setLrTodos(u); }}
                  placeholder={`Todo ${idx + 1}...`} style={styles.nameInput} />
              </div>
            ))}

            <button onClick={handleDownloadLearning}
              disabled={!learningFilled}
              style={{ ...styles.downloadButton, opacity: learningFilled ? 1 : 0.5, cursor: learningFilled ? 'pointer' : 'not-allowed' }}>
              Download PDF
            </button>
            {!learningFilled && <p style={styles.hint}>Fill in name, all learnings and todos to download.</p>}
          </div>
        )}
      </div>
    </div>
  );
}

const styles = {
  pageContainer: {
    minHeight: '100vh',
    padding: '30px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
  },
  header: {
    textAlign: 'center',
    position: 'relative',
    width: '100%',
    maxWidth: '800px',
  },
  backButton: {
    position: 'absolute',
    left: 0,
    top: 0,
    background: 'rgba(255,255,255,0.15)',
    border: 'none',
    color: 'white',
    padding: '8px 16px',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    backdropFilter: 'blur(10px)',
  },
  title: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: '2rem',
    fontWeight: '800',
    color: 'white',
    marginBottom: '6px',
  },
  subtitle: { color: 'rgba(255,255,255,0.85)', fontSize: '1rem' },
  // Tabs
  tabBar: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  tabActive: {
    background: 'white',
    color: '#0B2A5B',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '20px',
    fontSize: '0.9rem',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
  },
  tabInactive: {
    background: 'rgba(255,255,255,0.2)',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '20px',
    fontSize: '0.9rem',
    fontWeight: '600',
    cursor: 'pointer',
  },
  // Form card
  formCard: {
    background: 'white',
    borderRadius: '24px',
    padding: '36px 30px',
    width: '100%',
    maxWidth: '750px',
    boxShadow: '0 12px 40px rgba(0,0,0,0.2)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  formTitle: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: '1.3rem',
    fontWeight: '700',
    color: '#0B2A5B',
    textAlign: 'center',
    marginBottom: '4px',
  },
  subHeading: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: '1.05rem',
    fontWeight: '700',
    color: '#FF6B00',
    marginTop: '8px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  nameSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  nameLabel: {
    fontWeight: '700',
    fontSize: '0.9rem',
    color: '#0B2A5B',
  },
  smallLabel: {
    fontWeight: '600',
    fontSize: '0.85rem',
    color: '#555',
  },
  nameInput: {
    padding: '11px 14px',
    border: '2px solid #e0e0e0',
    borderRadius: '10px',
    fontSize: '0.95rem',
    outline: 'none',
    maxWidth: '100%',
  },
  textarea: {
    padding: '11px 14px',
    border: '2px solid #e0e0e0',
    borderRadius: '10px',
    fontSize: '0.95rem',
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  statementsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  statementRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '12px 14px',
    background: '#fafafa',
    borderRadius: '10px',
    border: '1px solid #eee',
  },
  negativeText: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '0.9rem',
    fontWeight: '600',
    color: '#c0392b',
  },
  number: { fontWeight: '700', color: '#555', minWidth: '18px' },
  responseRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    paddingLeft: '24px',
  },
  arrow: { fontSize: '1.1rem', color: '#27ae60', fontWeight: '700' },
  responseInput: {
    flex: 1,
    padding: '9px 12px',
    border: '2px solid #d4edda',
    borderRadius: '8px',
    fontSize: '0.9rem',
    outline: 'none',
    background: '#f8fff8',
  },
  downloadButton: {
    background: 'linear-gradient(135deg, #1E5EFF 0%, #0B2A5B 100%)',
    color: 'white',
    border: 'none',
    padding: '14px 32px',
    borderRadius: '30px',
    fontSize: '1rem',
    fontWeight: '700',
    cursor: 'pointer',
    alignSelf: 'center',
    boxShadow: '0 4px 15px rgba(30,94,255,0.3)',
    marginTop: '8px',
  },
  hint: { textAlign: 'center', fontSize: '0.8rem', color: '#999' },
};

export default Reflects;
